## COVID Drivers: Modeling

### Table of Contents
* [Read the Data](#read)</BR>

Import packages

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, QuantileTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
# Import project specific utilities
from utils.functions import *

In [ ]:
path_in = 'data/ready/ready_data.csv'

### <a id='read'>Read the data</a>

Read dataset created in covid_drivers_05_Prep.ipynb

In [ ]:
df_init = pd.read_csv(path_in, low_memory=False)

In [5]:
df_init.head()

,CRN,CRASH_DATE,AGGRESSIVE_DRIVING,NHTSA_AGG_DRIVING,NO_CLEARANCE,RUNNING_RED_LT,RUNNING_STOP_SIGN,SPEEDING,SPEEDING_RELATED,TAILGATING,POST_COVID
0,2005000003,2005-01-01,1,0,0,0,0,0,1,0,0
1,2005000006,2005-01-01,1,0,0,0,0,0,1,0,0
2,2005000010,2005-01-01,1,0,0,0,0,1,1,0,0
3,2005000012,2005-01-01,1,0,1,0,0,0,0,0,0
4,2005000013,2005-01-01,0,0,0,0,0,0,0,0,0

In [6]:
df_init.info()

<class 'pandas.DataFrame'>
RangeIndex: 2460484 entries, 0 to 2460483
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   CRN                 int64
 1   CRASH_DATE          str
 2   AGGRESSIVE_DRIVING  int64
 3   NHTSA_AGG_DRIVING   int64
 4   NO_CLEARANCE        int64
 5   RUNNING_RED_LT      int64
 6   RUNNING_STOP_SIGN   int64
 7   SPEEDING            int64
 8   SPEEDING_RELATED    int64
 9   TAILGATING          int64
 10  POST_COVID          int64
dtypes: int64(10), str(1)
memory usage: 206.5 MB

In [7]:
df_init['CRASH_DATE'] = pd.to_datetime(df_init['CRASH_DATE'])

In [8]:
summ_idx = df_init.copy().set_index('CRASH_DATE').drop(columns=['CRN'])

In [9]:
summ_idx.head()

,AGGRESSIVE_DRIVING,NHTSA_AGG_DRIVING,NO_CLEARANCE,RUNNING_RED_LT,RUNNING_STOP_SIGN,SPEEDING,SPEEDING_RELATED,TAILGATING,POST_COVID
CRASH_DATE,,,,,,,,,
2005-01-01,1,0,0,0,0,0,1,0,0
2005-01-01,1,0,0,0,0,0,1,0,0
2005-01-01,1,0,0,0,0,1,1,0,0
2005-01-01,1,0,1,0,0,0,0,0,0
2005-01-01,0,0,0,0,0,0,0,0,0

In [10]:
df = summ_idx.copy().resample('MS').mean()

In [13]:
behav_cols = ['NO_CLEARANCE',
 'RUNNING_RED_LT',
 'RUNNING_STOP_SIGN',
 'SPEEDING',
 'SPEEDING_RELATED',
 'TAILGATING']